version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
  install:
      - method: pip
        path: .
        extra_requirements:
          - rtd
          - theme_furo

sphinx:
  builder: html
  fail_on_warning: true
